name: Build and Test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Cache (dependencies)
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          GO111MODULE: "on"
        run: go mod download

      - name: Build
        env:
          GO111MODULE: "on"
        run: go build

      - name: Install linter
        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.0"

      - name: Test and Lint
        env:
          GO111MODULE: "on"
        run: |
          export PATH=${PATH}:$(go env GOPATH)/bin
          sh ./run_tests.sh
